export enum ActionNames {
	ROUTE_ACTION_TYPE = '@@Router/CALL_HISTORY_METHOD',
	ROUTE_ACTION_TYPE_ABS = '@@Router/CALL_HISTORY_METHOD_ABS',
	ROUTE_ACTION_TYPE_UP = '@@Router/CALL_HISTORY_METHOD_UP',
	ROUTE_ACTION_SET_LINKS = '@@Router/SET_LINKS',
}
